-- Query 1, demonstrates basic query of APP_CAR
SELECT CARMANUFACTURER, CARMODEL
FROM APP_CAR
WHERE CARYEAR = '2016'
ORDER BY CARMANUFACTURER DESC;

-- Query 2, demonstrates use of *
SELECT  *
FROM APP_USER
WHERE USERID = 22;

-- Query 3, demonstrates implicit join as well as sorting
SELECT A.LICENSENO, U.USERNAME
FROM APP_CAR A, APP_USER U
WHERE A.OWNERID = U.USERID
ORDER BY U.USERNAME;

-- Query 4, demonstrates explicit join
SELECT A.CARMANUFACTURER, U.USERNAME
FROM APP_CAR A LEFT OUTER JOIN APP_USER U ON A.OWNERID = U.USERID
WHERE U.USERNAME = 'Jack McOrallo';

-- Query 5, demonstrates LIKE keyword
SELECT USERNAME, USERID
FROM APP_USER
WHERE USERADDRESS LIKE '%New York%'
ORDER BY USERNAME ASC;

-- Query 6, demonstrates BETWEEN keyword
SELECT DESTINATION, DEPARTURETIME
FROM TRIP_HISTORY
WHERE NUMRIDERS BETWEEN 1 AND 4
ORDER BY DEPARTURETIME ASC;

-- Query 7, demonstrates IN keyword
SELECT DEPARTURETIME
FROM APP_TRIP_INFO 
WHERE DESTINATION IN (SELECT DESTINATION 
                    FROM TRIP_HISTORY 
                    WHERE NUMRIDERS = 3);

-- Query 8, demonstrates ROUND and AVG (example of an aggregate function)
SELECT CARMANUFACTURER, ROUND(AVG(NUMSEATS)) AS AVERAGESEATS
FROM APP_CAR
GROUP BY CARMANUFACTURER;

-- Query 9, demonstrates count DISTINCT
SELECT COUNT(DISTINCT CARMODEL) AS UNIQUECARMODELS
FROM APP_CAR;

-- Query 10, 11, and 12, demonstrates GROUP BY and HAVING
SELECT CARLICENSE, COUNT(TRIPID) AS NUMBEROFTRIPS
FROM APP_TRIP_INFO
GROUP BY CARLICENSE
HAVING COUNT(TRIPID) >= 2;

SELECT OWNERID, COUNT(LICENSENO) AS NUMBEROFCARS
FROM APP_CAR
GROUP BY OWNERID
HAVING COUNT(LICENSENO) > 1;

SELECT DESTINATION, AVG(NUMRIDERS) AS AVERAGERIDERS, COUNT(TRIPID) AS TOTALTRIPS
FROM APP_TRIP_INFO
GROUP BY DESTINATION
ORDER BY AVERAGERIDERS DESC;

-- Query 13, demonstrates nested query
SELECT USERNAME 
FROM APP_USER
WHERE USERID = (SELECT OWNERID FROM APP_CAR WHERE CARMANUFACTURER = 'Range Rover');

-- Query 14, demonstrates JOIN ON
SELECT AU.USERNAME, AC.CARMODEL
FROM APP_USER AU
JOIN APP_CAR AC ON AU.USERID = AC.OWNERID;






